# GALAXIA 3

* Exercício 30: Peça pro usuário inputar a cotação de 3 ações. Crie um array de cotações.


In [4]:
import numpy as np
acoes = []

for i in range(1,4):
    acoes.append(float(input(f"cotação {i}")))

acoes = np.array(acoes)
print(acoes)
vetor_aleatorio_inteiro = np.random.randint(low = 0, high = 10, size = 3)

[1. 1. 1.]


* Exercício 31: Peça pro usuário digitar dois números no programa e crie um arrange sequencial entre esse números.


In [6]:
begin = int(input("Digite o inicio da lista"))
end = int(input("Digite o fim da lista"))

vetor = np.arange(begin, end+1)
print(vetor)


[ 1  2  3  4  5  6  7  8  9 10 11]


* Exercício 32: Crie um programa que gere numeros aleatórios inteiros entre 0 e 60 e devolva 6 números da mega sena pro usuário. Depois, exiba uma probabilidade aleatória de o usuário sair vencedor. Garanta que sejam 6 números diferentes!

In [105]:
vetor_aleatorio_inteiro = np.random.choice(range(61), size=6, replace=False)
print(vetor_aleatorio_inteiro)
p = round(np.random.uniform(0,100),2)
p2 = np.random.uniform(0,100)
print(f"Probabilidade de vencer: {p}")
print(f"Probabilidade de vencer 2: {p2:.2f}")



[47 59  6 33 51 40]
Probabilidade de vencer: 93.48
Probabilidade de vencer 2: 60.55


# MUNDO 3

# DESAFIO

# MUNDO 4

## EXERCICIO

* Exercício 33: Faça um programa que gere um vetor de retornos positivos ou negativos entre -1 e 1 na quantidade de dias que o usuário escolher. Devolva um vetor dos retornos positivos, o primeiro e o último retorno.

In [114]:
dias = int(input("Digite a quantidade de dias:"))

aleatorios = np.random.uniform(-1,1, dias)
positivos = aleatorios[aleatorios>0]

print(f"primeiro: {positivos[0]}")
print(f"ultimo: {positivos[-1]}")

print(positivos)

primeiro: 0.2884569171392044
ultimo: 0.6893272214572412
[0.28845692 0.19452778 0.87798864 0.92450713 0.80432929 0.51517767
 0.64142427 0.68932722]


In [ ]:
dias = int(input("Digite quantos retornos devem ser gerados: "))

retorno_aleatorio = np.random.uniform(-1, 1, dias)

retornos_positivos = retorno_aleatorio[retorno_aleatorio > 0]

print(f'''Os retornos positivos são {retornos_positivos} 
        O primeiro retorno é {retornos_positivos[0]} e o último é {retornos_positivos[-1]}''')

# Mundo 5

In [ ]:
#* Exercício 34: Peça ao usuário digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior pro menor. (Utilize arrays e ferramentas como append, np.sort, etc)

In [ ]:
empresas = np.array(["Weg", "Vale", "Petrobras"])

array_lucros = np.array([])

for empresa in empresas:
    
    lucro = float(input(f"Digite o lucro da {empresa}: "))
    array_lucros = np.append(array_lucros, lucro)

array_lucros = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior pro menor: {array_lucros}')

In [115]:
empresas = np.array(["WEG", "VALE","PETROBRAS"])

array_lucros = np.array([])


for empresa in empresas:
    
    lucro = float(input(f"Digite o lucro da empresa {empresa}"))
    array_lucros = np.append(array_lucros, lucro)
    
    
array_lucros = -np.sort(-array_lucros)


print(f"Lucro das empresas do maior ao menor: {array_lucros}")
    
    
    
    
    
    
    

Lucro das empresas do maior ao menor: [3. 2. 1.]


In [ ]:
petrobras = float(input("Lucro petrobras"))
vale = float(input("Lucro vale"))
weg = float(input("Lucro weg"))




# MUNDO 6

In [116]:
continuar = True

array_rentabilidade = np.array([])

while(continuar):
    
    rent = float(input("Digite uma rentabilidade:"))
    
    array_rentabilidade = np.append(array_rentabilidade, rent)
    
    deseja_continuar = str(input("Deseja cadastrar mais rentabilidades?S/N")).lower()
    
    if (deseja_continuar == 'n'):
        break

media = np.mean(array_rentabilidade)
mediana = np.median(array_rentabilidade)
desvio = np.std(array_rentabilidade)
rent_max = np.max(array_rentabilidade)
rent_min = np.min(array_rentabilidade)




media = "{:.0%}".format(media)
mediana = "{:.0%}".format(mediana)
desvio_padrao = "{:.0%}".format(desvio)
rent_max = "{:.0%}".format(rent_max)
rent_min = "{:.0%}".format(rent_min)

print("")
print("Aqui estão as estatísticas das rentabilidades:")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Desvio padrão: {desvio_padrao}")
print(f"Rentabilidade máxima: {rent_max}")
print(f"Rentabilidade mínima: {rent_min}")





Aqui estão as estatísticas das rentabilidades:
Média: 200%
Mediana: 200%
Desvio padrão: 82%
Rentabilidade máxima: 300%
Rentabilidade mínima: 100%


In [ ]:
continuar = True

array_rentabilidade = np.array([])

while continuar:

    rent = float(input("Digite uma rentabilidade: "))

    array_rentabilidade = np.append(array_rentabilidade, rent)

    deseja_continuar = str(input("Deseja cadastrar mais rentabilidades? [S/N]")).lower()

    if deseja_continuar != "n" and deseja_continuar != "s":

        invalido = True

        while invalido:

            deseja_continuar = str(input("Por favor, digite um comando válido: [S/N]")).lower()

            if deseja_continuar == "n" or deseja_continuar == "s":

                break

    if deseja_continuar == "n":

        break

media = np.mean(array_rentabilidade)
mediana = np.median(array_rentabilidade)
desvio_padrao = np.std(array_rentabilidade)
rent_max = array_rentabilidade.max()
rent_min = array_rentabilidade.min()

media = "{:.0%}".format(media)
mediana = "{:.0%}".format(mediana)
desvio_padrao = "{:.0%}".format(desvio_padrao)
rent_max = "{:.0%}".format(rent_max)
rent_min = "{:.0%}".format(rent_min)

print("")
print("Aqui estão as estatísticas das rentabilidades:")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Desvio padrão: {desvio_padrao}")
print(f"Rentabilidade máxima: {rent_max}")
print(f"Rentabilidade mínima: {rent_min}")