# Mundo 4

In [1]:
import numpy as np

In [4]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

vetor2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(vetor)
print(vetor2d)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#posições

print(vetor[0])

print(vetor[0:2])

print(vetor[-1])

print(vetor2d[2][0])
print(vetor2d[0][1])

1
[1 2]
9
7
2


In [6]:
#filtrando dados

vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

maior_que_5 = vetor[vetor > 5]

somente_par = vetor[vetor % 2 == 0]

igual_a_5 = vetor[vetor == 5]

maior_que_3_menor_que_8 = vetor[ (vetor > 5) & (vetor < 8)] 

print(maior_que_5)
print(somente_par)
print(igual_a_5)
print(maior_que_3_menor_que_8)

[6 7 8 9]
[2 4 6 8]
[5]
[6 7]


# Exercício

* Exercício 33: Faça um programa que gere um vetor de retornos positivos ou negativos entre -1 e 1 na quantidade de dias que o usuário escolher. Devolva um vetor dos retornos positivos, o primeiro e o último retorno.

In [ ]:
dias = int(input("Digite quantos retornos devem ser gerados: "))

retorno_aleatorio = np.random.uniform(-1, 1, dias)

retornos_positivos = retorno_aleatorio[retorno_aleatorio > 0]

print(f'''Os retornos positivos são {retornos_positivos} 
        O primeiro retorno é {retornos_positivos[0]} e o último é {retornos_positivos[-1]}''')

Digite quantos retornos devem ser gerados: 5
Os retornos positivos são [0.60856617 0.06255511 0.92303492 0.86236994] 
        O primeiro retorno é 0.6085661682050787 e o último é 0.8623699352162697


# Mundo 5

Essas últimas duas aulas foram rápidas e bem simples. Nos mundos 5 e 6 nós vamos mais a fundo no numpy, descobrindo como podemos fazer conta, extrair
estatísticas, juntar arrays, rankear arrays, adicionar e excluir dados e muito mais. No mundo 5 descobrir como manipular esses arrays da melhor forma!