# Mundo 6

In [2]:
import numpy as np

In [5]:
#todas as operações funcionam com os vetores.

array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])
array3 = np.array([2, 2])

lista_normal = [1, 1, 1, 1]
lista_normal2 = [4, 2, 6, 2]

print(array1 + array2)
print(lista_normal + lista_normal2)

[5 3 7 3]
[1, 1, 1, 1, 4, 2, 6, 2]


In [4]:
print(array1 + array3)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [6]:
#E se eu quiser somar um número só?

soma_a_todos_os_elementos = np.array([1, 1, 1, 1]) + 20

print(soma_a_todos_os_elementos)

[21 21 21 21]


In [7]:
#todas as operações funcionam normal
array1 = np.array([1, 1, 1, 1])
array2 = np.array([4, 2, 6, 2])

subtracao = array1 - array2
divisao = array1/array2
multiplicacao = array1 * array2
exponenciacao = array1 ** array2

print(subtracao)
print(divisao)
print(multiplicacao)
print(exponenciacao)

[-3 -1 -5 -1]
[0.25       0.5        0.16666667 0.5       ]
[4 2 6 2]
[1 1 1 1]


In [8]:
#Operações dentro do próprio vetor

vetor = np.array([1, 4, -4, -1, 2])

print(vetor)
print(vetor.sum())
print(vetor.max())
print(vetor.min())
print(np.abs(vetor))

[ 1  4 -4 -1  2]
2
4
-4
[1 4 4 1 2]


In [9]:
#Estatisticas descritivas

vetor = np.array([1, 20, -4, -12, 2000])

media = np.mean(vetor)
mediana = np.median(vetor)
desvio_p = np.std(vetor)
var = np.var(vetor)

print(media) #media
print(mediana) #mediana
print(desvio_p) #desvio padrao
print(var) #variancia

401.0
1.0
799.56938410622
639311.2


In [10]:
#matriz de correlação 
vetor = np.array([1, 20, -4, -12, 2000])

vetor2 = np.array([5, 4, 3, -5, 4])
vetor3 = np.array([2, 6, 7, -5, 1])

correlacao = np.corrcoef((vetor, vetor2, vetor3))

correlacao

array([[ 1.        ,  0.25471058, -0.13247913],
       [ 0.25471058,  1.        ,  0.76783876],
       [-0.13247913,  0.76783876,  1.        ]])

# Exercício

* Exercício 35: Faça um programa que o usuário digite a rentabilidade de ações, com quantas ações o usuário quiser. Transforme essas listas em arrays e devolva pro usuário:

        A média de rentabilidade da carteira.
        O Desvio padrão da carteira.
        A mediana de retornos da carteira.
        O maior retorno.
        O menor retorno.

In [ ]:
continuar = True

array_rentabilidade = np.array([])

while continuar:

    rent = float(input("Digite uma rentabilidade: "))

    array_rentabilidade = np.append(array_rentabilidade, rent)

    deseja_continuar = str(input("Deseja cadastrar mais rentabilidades? [S/N]")).lower()

    if deseja_continuar != "n" and deseja_continuar != "s":

        invalido = True

        while invalido:

            deseja_continuar = str(input("Por favor, digite um comando válido: [S/N]")).lower()

            if deseja_continuar == "n" or deseja_continuar == "s":

                break

    if deseja_continuar == "n":

        break

media = np.mean(array_rentabilidade)
mediana = np.median(array_rentabilidade)
desvio_padrao = np.std(array_rentabilidade)
rent_max = array_rentabilidade.max()
rent_min = array_rentabilidade.min()

media = "{:.0%}".format(media)
mediana = "{:.0%}".format(mediana)
desvio_padrao = "{:.0%}".format(desvio_padrao)
rent_max = "{:.0%}".format(rent_max)
rent_min = "{:.0%}".format(rent_min)

print("")
print("Aqui estão as estatísticas das rentabilidades:")
print(f"Média: {media}")
print(f"Mediana: {mediana}")
print(f"Desvio padrão: {desvio_padrao}")
print(f"Rentabilidade máxima: {rent_max}")
print(f"Rentabilidade mínima: {rent_min}")

Digite uma rentabilidade: 0.2
Deseja cadastrar mais rentabilidades? [S/N]vosvisivj
Por favor, digite um comando válido: [S/N]s
Digite uma rentabilidade: 0.3
Deseja cadastrar mais rentabilidades? [S/N]s
Digite uma rentabilidade: 0.65
Deseja cadastrar mais rentabilidades? [S/N]n

Aqui estão as estatísticas das rentabilidades:
Média: 38%
Mediana: 30%
Desvio padrão: 19%
Rentabilidade máxima: 65%
Rentabilidade mínima: 20%


# Galáxia 4

Fim do módulo do Numpy! Na galáxia 4 nós iremos abordar o módulo Pandas, a principal biblioteca de análise de dados que existe.
Vamos aprender a puxar cotações, criar médias móveis, tratar dados, ler planilhas de excel e muito mais. Te vejo lá!