# Mundo 5

In [2]:
import numpy as np

In [5]:
#juntar dois arrays

array1 = np.arange(20, 25)
array2 = np.arange(15)

array_completo = np.concatenate([array1, array2])

print(array_completo)

[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
#separando em dois arrays

array_separado1, array_separado2 = np.split(array_completo, [10])

print(array_separado1)
print(array_separado2)

[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]


In [9]:
#colocar novos dados em um array

#[20 21 22 23 24  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

array_completo = np.append(array_completo, 2000)

array_completo = np.insert(array_completo, 3,  3000)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14 2000]


In [10]:
#deletar dados de um array

array_completo = np.delete(array_completo, -1)

print(array_completo)

[  20   21   22 3000   23   24    0    1    2    3    4    5    6    7
    8    9   10   11   12   13   14]


In [11]:
#reshape

array_3x3 = np.arange(9).reshape(3, 3) #isso aqui é util na hora de fazer regressão linear

print(array_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#trocando números dentro de uma condição

array_inicial = np.array([4, 4, 4, 4, 7, 6, 5, 32, 13, 2, 32, 675, 74, 465])

#como trocar todos os numero menores que 40 por 0?

array_inicial[array_inicial < 40] = 0

print(array_inicial)

[  0   0   0   0   0   0   0   0   0   0   0 675  74 465]


In [15]:
#como ordernar objetos dentro de uma lista?

array_desordenado = np.array([23109, 2349, 349, 20, 3, 5, 12490])

array_crescente = np.sort(array_desordenado)
array_decrescente = -np.sort(-array_desordenado)

print(array_crescente, array_decrescente)

[    3     5    20   349  2349 12490 23109] [23109 12490  2349   349    20     5     3]


# Exercício

* Exercício 34: Peça ao usuário digitar o lucro da Petrobras, Vale e Weg. Mostre os lucros em ordem do maior pro menor. (Utilize arrays e ferramentas como append, np.sort, etc)

In [ ]:
empresas = np.array(["Weg", "Vale", "Petrobras"])

array_lucros = np.array([])

for empresa in empresas:
    
    lucro = float(input(f"Digite o lucro da {empresa}: "))
    array_lucros = np.append(array_lucros, lucro)

array_lucros = -np.sort(-array_lucros)

print(f'Lucro das empresas, do maior pro menor: {array_lucros}')

Digite o lucro da Weg: 20
Digite o lucro da Vale: 50
Digite o lucro da Petrobras: 80
Lucro das empresas, do maior pro menor: [80. 50. 20.]


# Mundo 6

Bom, agora que você já aprendeu a manipular arrays, como a gente pode fazer operações com arrays, que é o mais importante no numpy?
Como calcula média, desvio padrão? No mundo 6 a gente vai descobrir! 